/* Reptile Log - species reference data. Commonly published husbandry targets for healthy adults.
   Temperatures F. rh = relative humidity %. feedInterval = days between offerings for an adult.
   Sources are mainstream care guides; individuals, locality and life stage move these numbers. */
(function (root) {
  'use strict';
  const S = [
    // ---- snakes ----
    { n: 'Ball python', g: 'Snake', hot: 90, cool: 79, bask: null, rh: [55, 65], rhShed: 70, night: 75, uvb: 'Optional, low', interval: 12, juv: 6, diet: 'One appropriately sized frozen-thawed rodent', size: '3 to 5 ft', life: '20 to 30 years', supp: 'None needed', note: 'Long winter fasts are normal in healthy adults; log weight every two weeks instead of worrying.' },
    { n: 'Corn snake', g: 'Snake', hot: 86, cool: 75, bask: null, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Optional, low', interval: 10, juv: 5, diet: 'Frozen-thawed mouse', size: '4 to 5 ft', life: '15 to 20 years', supp: 'None needed', note: 'Escape artist: check the lid latch every visit.' },
    { n: 'King snake', g: 'Snake', hot: 86, cool: 75, bask: null, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Optional, low', interval: 10, juv: 5, diet: 'Frozen-thawed rodent', size: '3 to 6 ft', life: '15 to 20 years', supp: 'None needed', note: 'Housed alone, always: kingsnakes eat other snakes.' },
    { n: 'Milk snake', g: 'Snake', hot: 85, cool: 74, bask: null, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Optional, low', interval: 10, juv: 5, diet: 'Frozen-thawed rodent', size: '2 to 5 ft', life: '15 to 20 years', supp: 'None needed', note: 'Shy; plenty of hides on both sides.' },
    { n: 'Boa constrictor', g: 'Snake', hot: 90, cool: 80, bask: null, rh: [55, 70], rhShed: 75, night: 78, uvb: 'Optional, low', interval: 21, juv: 10, diet: 'Frozen-thawed rodent', size: '6 to 10 ft', life: '25 to 30 years', supp: 'None needed', note: 'Gets big and strong; a second person for handling once past about 6 ft.' },
    { n: 'Rosy boa', g: 'Snake', hot: 88, cool: 72, bask: null, rh: [30, 50], rhShed: 60, night: 68, uvb: 'Optional, low', interval: 10, juv: 6, diet: 'Frozen-thawed mouse', size: '2 to 3 ft', life: '18 to 25 years', supp: 'None needed', note: 'Dry species; wet substrate causes scale rot.' },
    { n: 'Sand boa', g: 'Snake', hot: 95, cool: 75, bask: null, rh: [30, 40], rhShed: 50, night: 72, uvb: 'Optional, low', interval: 10, juv: 6, diet: 'Frozen-thawed mouse', size: '1.5 to 3 ft', life: '20 years', supp: 'None needed', note: 'Burrows; deep aspen or sand-soil mix, expect to see only the head.' },
    { n: 'Hognose snake', g: 'Snake', hot: 90, cool: 75, bask: null, rh: [30, 50], rhShed: 60, night: 72, uvb: 'Optional, low', interval: 7, juv: 5, diet: 'Frozen-thawed mouse, scented if needed', size: '1.5 to 3 ft', life: '15 to 20 years', supp: 'None needed', note: 'Bluffing displays (hooding, playing dead) are theatre, not illness.' },
    { n: 'Carpet python', g: 'Snake', hot: 90, cool: 78, bask: 92, rh: [50, 60], rhShed: 70, night: 74, uvb: 'Optional, low', interval: 14, juv: 7, diet: 'Frozen-thawed rodent', size: '5 to 9 ft', life: '20 years', supp: 'None needed', note: 'Arboreal; branches and a high perch matter more than floor space.' },
    { n: 'Green tree python', g: 'Snake', hot: 86, cool: 76, bask: 88, rh: [60, 80], rhShed: 85, night: 74, uvb: 'Optional, low', interval: 14, juv: 7, diet: 'Frozen-thawed rodent, offered on the perch', size: '4 to 6 ft', life: '20 years', supp: 'None needed', note: 'Advanced keeper species; humidity and ventilation must both be right.' },
    { n: 'Garter snake', g: 'Snake', hot: 85, cool: 72, bask: 88, rh: [40, 60], rhShed: 65, night: 65, uvb: 'Optional, low', interval: 5, juv: 3, diet: 'Fish (thiaminase-free), earthworms, rodents', size: '2 to 3 ft', life: '10 years', supp: 'Calcium with D3 on fish', note: 'Feeds often; avoid goldfish and other thiaminase-rich fish.' },
    { n: 'Reticulated python', g: 'Snake', hot: 90, cool: 80, bask: null, rh: [60, 70], rhShed: 75, night: 78, uvb: 'Optional, low', interval: 21, juv: 10, diet: 'Frozen-thawed rodent or rabbit', size: '10 to 20 ft', life: '20 to 25 years', supp: 'None needed', note: 'Large constrictor: two adults present for any handling, and check local rules.' },
    { n: 'Blood python', g: 'Snake', hot: 88, cool: 78, bask: null, rh: [60, 70], rhShed: 75, night: 76, uvb: 'Optional, low', interval: 14, juv: 7, diet: 'Frozen-thawed rodent', size: '4 to 6 ft', life: '20 years', supp: 'None needed', note: 'Heavy-bodied and humidity-sensitive; watch for respiratory signs if it dries out.' },
    // ---- geckos ----
    { n: 'Leopard gecko', g: 'Gecko', hot: 90, cool: 77, bask: null, rh: [30, 40], rhShed: 60, night: 70, uvb: 'Optional, low', interval: 3, juv: 1, diet: 'Dusted insects: crickets, dubia, black soldier fly larvae', size: '8 to 10 in', life: '15 to 20 years', supp: 'Calcium most feedings, D3 1 to 2x weekly without UVB, multivitamin every 1 to 2 weeks', note: 'Belly heat from a mat or DHP on a thermostat; a humid hide prevents stuck shed on toes.' },
    { n: 'Crested gecko', g: 'Gecko', hot: 78, cool: 70, bask: null, rh: [60, 80], rhShed: 80, night: 68, uvb: 'Optional, low', interval: 2, juv: 1, diet: 'Complete crested gecko diet, insects weekly', size: '7 to 9 in', life: '15 to 20 years', supp: 'In the diet; dust insects with calcium', note: 'Above about 82F is dangerous. Let the enclosure dry out between mistings.' },
    { n: 'Gargoyle gecko', g: 'Gecko', hot: 78, cool: 70, bask: null, rh: [60, 75], rhShed: 80, night: 68, uvb: 'Optional, low', interval: 2, juv: 1, diet: 'Complete gecko diet, insects weekly', size: '7 to 9 in', life: '15 to 20 years', supp: 'In the diet; dust insects with calcium', note: 'Same heat ceiling as cresteds; will eat other geckos, so house alone.' },
    { n: 'Leachianus gecko', g: 'Gecko', hot: 78, cool: 70, bask: null, rh: [60, 75], rhShed: 80, night: 68, uvb: 'Optional, low', interval: 3, juv: 2, diet: 'Complete gecko diet, insects, occasional pinky', size: '12 to 17 in', life: '20 years', supp: 'In the diet; calcium on insects', note: 'Largest gecko; tall enclosure with a cork tube.' },
    { n: 'African fat-tailed gecko', g: 'Gecko', hot: 90, cool: 77, bask: null, rh: [50, 60], rhShed: 70, night: 72, uvb: 'Optional, low', interval: 3, juv: 1, diet: 'Dusted insects', size: '7 to 9 in', life: '15 to 20 years', supp: 'Calcium most feedings, D3 weekly without UVB, multivitamin biweekly', note: 'Needs more humidity than a leopard gecko; always a moist hide.' },
    { n: 'Tokay gecko', g: 'Gecko', hot: 88, cool: 75, bask: null, rh: [60, 80], rhShed: 80, night: 72, uvb: 'Optional, low', interval: 3, juv: 1, diet: 'Dusted insects', size: '10 to 15 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Bites hard and does not let go. Display animal, not a handling animal.' },
    { n: 'Day gecko (Phelsuma)', g: 'Gecko', hot: 85, cool: 75, bask: 88, rh: [60, 80], rhShed: 80, night: 70, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects and fruit-based gecko diet', size: '5 to 10 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Diurnal and fast; delicate skin, handling is discouraged.' },
    // ---- lizards ----
    { n: 'Bearded dragon', g: 'Lizard', hot: 95, cool: 78, bask: 105, rh: [30, 40], rhShed: 50, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Adults mostly greens daily, insects 2 to 3 times a week', size: '18 to 24 in', life: '8 to 12 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Basking surface temperature, not air. No loose sand for juveniles.' },
    { n: 'Blue-tongue skink', g: 'Lizard', hot: 90, cool: 78, bask: 100, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Required, medium', interval: 3, juv: 2, diet: 'Omnivore mix: greens, vegetables, protein, some fruit', size: '18 to 24 in', life: '15 to 20 years', supp: 'Calcium on protein, multivitamin weekly', note: 'Indonesian species want higher humidity than Australian ones; check the locality.' },
    { n: 'Veiled chameleon', g: 'Lizard', hot: 82, cool: 72, bask: 90, rh: [50, 70], rhShed: 75, night: 65, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Dusted insects, adults every other day', size: '14 to 24 in', life: '5 to 8 years', supp: 'Calcium most feedings, D3 and multivitamin every 2 weeks', note: 'Screen enclosure, dripper or misting system; drinks moving water only.' },
    { n: 'Panther chameleon', g: 'Lizard', hot: 82, cool: 72, bask: 88, rh: [60, 80], rhShed: 80, night: 65, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Dusted insects', size: '14 to 20 in', life: '5 to 7 years', supp: 'Calcium most feedings, D3 and multivitamin every 2 weeks', note: 'Higher humidity than veiled; a night drop is normal and healthy.' },
    { n: 'Green anole', g: 'Lizard', hot: 85, cool: 72, bask: 90, rh: [60, 70], rhShed: 75, night: 65, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Small dusted insects', size: '5 to 8 in', life: '4 to 8 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Drinks droplets from leaves; mist daily.' },
    { n: 'Green iguana', g: 'Lizard', hot: 90, cool: 78, bask: 100, rh: [60, 80], rhShed: 80, night: 73, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Greens and vegetables daily, no animal protein', size: '5 to 6 ft', life: '15 to 20 years', supp: 'Calcium daily for juveniles, multivitamin weekly', note: 'Needs a room-sized enclosure as an adult. Most are rehomed; think hard first.' },
    { n: 'Argentine tegu', g: 'Lizard', hot: 90, cool: 78, bask: 105, rh: [60, 80], rhShed: 80, night: 72, uvb: 'Required, high', interval: 3, juv: 1, diet: 'Whole prey, insects, eggs, some fruit', size: '3 to 4.5 ft', life: '15 to 20 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Brumates for months; deep substrate for burrowing.' },
    { n: 'Uromastyx', g: 'Lizard', hot: 95, cool: 80, bask: 120, rh: [20, 30], rhShed: 35, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Seeds, greens and flowers; no insects needed for most', size: '10 to 18 in', life: '15 to 20 years', supp: 'Calcium on greens, multivitamin weekly', note: 'Very hot and very dry; water bowls can cause problems, hydration comes from greens.' },
    { n: 'Crested / Chinese water dragon', g: 'Lizard', hot: 88, cool: 78, bask: 95, rh: [70, 80], rhShed: 85, night: 72, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, some greens and protein', size: '2 to 3 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Tall, planted, humid enclosure with a large water area; glass surfing damages the snout.' },
    { n: 'Leopard / ocellated skink', g: 'Lizard', hot: 90, cool: 75, bask: 95, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects and some plant matter', size: '6 to 12 in', life: '10 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Burrower; deep substrate and secure hides.' },
    { n: 'Gold dust / common house gecko', g: 'Gecko', hot: 85, cool: 75, bask: null, rh: [60, 70], rhShed: 75, night: 72, uvb: 'Optional, low', interval: 2, juv: 1, diet: 'Small dusted insects', size: '4 to 6 in', life: '5 to 10 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Fast and fragile; a display animal.' },
    // ---- monitors (Varanus) ----
    // Basking figures for monitors are SURFACE temperatures under the lamp, read with an infrared gun,
    // not air temperature. Almost all want deep, moist, burrowable substrate and an enclosure far larger
    // than a comparable lizard: a bioactive-style setup is closer to correct than a glass tank.
    { n: 'Ackie monitor (spiny-tailed)', g: 'Monitor', hot: 95, cool: 82, bask: 155, rh: [60, 80], rhShed: 80, night: 76, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects: dubia, crickets, snails, black soldier fly larvae; occasional egg or whole prey', size: '24 to 30 in', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Red and yellow ackies are the same species. Basking surface 150 to 160F measured with an IR gun; 12 to 18 in of moist substrate to burrow in. The best first monitor by a wide margin.' },
    { n: 'Storr\'s monitor', g: 'Monitor', hot: 92, cool: 80, bask: 145, rh: [50, 60], rhShed: 70, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '12 to 16 in', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'The smallest monitor commonly kept, and drier than an ackie. Still wants a deep substrate and a hot basking surface.' },
    { n: 'Timor monitor', g: 'Monitor', hot: 90, cool: 78, bask: 130, rh: [60, 70], rhShed: 80, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, occasional whole prey', size: '18 to 24 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Semi-arboreal and nervous: tall enclosure, cork tubes, and a lot of cover. Rarely becomes a handling animal.' },
    { n: 'Kimberley rock monitor', g: 'Monitor', hot: 90, cool: 78, bask: 135, rh: [60, 70], rhShed: 80, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, occasional egg or whole prey', size: '24 to 30 in', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Climbs rock and bark rather than digging deep. Stacked slate or cork with tight crevices, secured so it cannot topple.' },
    { n: 'Pilbara rock monitor', g: 'Monitor', hot: 90, cool: 78, bask: 140, rh: [50, 65], rhShed: 75, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects', size: '18 to 24 in', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Small, fast and rock-dwelling. Drier than the Kimberley; same rule about securing the rockwork.' },
    { n: 'Black-headed / freckled monitor', g: 'Monitor', hot: 92, cool: 78, bask: 140, rh: [50, 70], rhShed: 80, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, occasional whole prey', size: '24 to 30 in', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Two subspecies of Varanus tristis, both semi-arboreal. Wants height and hot basking together.' },
    { n: 'Savannah monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [60, 80], rhShed: 80, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects as the staple: dubia, snails, crayfish; whole prey occasionally, not as a diet', size: '3 to 4 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'The most commonly killed monitor in the hobby: dry tanks and a rodent diet cause obesity, gout and early death. Insects, 2 ft of moist substrate, 8 x 4 ft floor minimum.' },
    { n: 'White-throated monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [60, 70], rhShed: 80, night: 75, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Insects, snails, occasional whole prey', size: '4 to 5 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Larger and longer-lived than a savannah, with the same husbandry. Plan a custom enclosure before buying the animal.' },
    { n: 'Black-throated monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [60, 70], rhShed: 80, night: 75, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Insects, snails, occasional whole prey', size: '4 to 5.5 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Often the most tractable of the large monitors, which does not make it a beginner animal. Room-sized enclosure as an adult.' },
    { n: 'Argus monitor', g: 'Monitor', hot: 95, cool: 80, bask: 150, rh: [60, 80], rhShed: 80, night: 76, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, whole prey, eggs', size: '3.5 to 4.5 ft', life: '12 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Very high activity and very high basking surface. Tail whips hard; bites are serious. Experienced keepers only.' },
    { n: 'Peach-throated monitor', g: 'Monitor', hot: 90, cool: 78, bask: 125, rh: [70, 80], rhShed: 85, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, fish, whole prey', size: '3 to 3.5 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Tropical and humidity-dependent; wild-caught imports are common and usually arrive with parasites. Quarantine and a fecal test are not optional.' },
    { n: 'Mangrove monitor', g: 'Monitor', hot: 90, cool: 80, bask: 130, rh: [70, 90], rhShed: 90, night: 76, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, fish, crustaceans, eggs, occasional whole prey', size: '3 to 4 ft', life: '12 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Semi-aquatic: a water area big enough to submerge in, with filtration. High humidity and high ventilation at the same time.' },
    { n: 'Dumeril\'s monitor', g: 'Monitor', hot: 90, cool: 78, bask: 125, rh: [70, 90], rhShed: 90, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, crabs and crustaceans, fish', size: '3 to 4 ft', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Shy and easily stressed: heavy cover, a large water area, and as little traffic past the enclosure as you can manage.' },
    { n: 'Black roughneck monitor', g: 'Monitor', hot: 90, cool: 78, bask: 125, rh: [70, 85], rhShed: 90, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, snails, crustaceans, occasional whole prey', size: '3 to 4 ft', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Arboreal and famously shy. Tall, planted, humid enclosure with cork tubes high up; a stressed roughneck stops eating.' },
    { n: 'Quince monitor', g: 'Monitor', hot: 90, cool: 78, bask: 130, rh: [70, 85], rhShed: 90, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, eggs, fish, occasional whole prey', size: '3 to 4 ft', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Bright yellow member of the mangrove group; same humid, semi-arboreal setup. Captive-bred animals settle far better than imports.' },
    { n: 'Green tree monitor', g: 'Monitor', hot: 88, cool: 78, bask: 120, rh: [70, 90], rhShed: 90, night: 74, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '2.5 to 3 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Delicate and fully arboreal: height over floor space, dense foliage, misting, and a lower basking temperature than terrestrial monitors. Not a handling animal.' },
    { n: 'Blue tree monitor', g: 'Monitor', hot: 88, cool: 78, bask: 120, rh: [70, 90], rhShed: 90, night: 74, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '3 to 3.5 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Same care as the green tree monitor, at a higher price and with the same fragility. Escapes through any gap it can fit its head through.' },
    { n: 'Nile monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [70, 80], rhShed: 85, night: 76, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Insects, fish, crustaceans, whole prey', size: '4 to 6 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Large, fast, semi-aquatic and genuinely dangerous when defensive. Restricted or prohibited in some states and cities, Florida among them: check the law before acquiring one.' },
    { n: 'Asian water monitor', g: 'Monitor', hot: 92, cool: 82, bask: 140, rh: [70, 90], rhShed: 90, night: 78, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Fish, insects, crustaceans, whole prey, eggs', size: '5 to 8 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Needs a heated room, not an enclosure, plus a pool it can submerge in. Adults are strong enough to cause serious injury. Check state and local law.' },
    { n: 'Crocodile monitor', g: 'Monitor', hot: 90, cool: 80, bask: 135, rh: [70, 85], rhShed: 90, night: 76, uvb: 'Required, high', interval: 4, juv: 2, diet: 'Whole prey, fish, eggs', size: '7 to 10 ft', life: '12 to 20 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Arboreal, very long-tailed, with a bite that needs hospital treatment. Two experienced people for any enclosure work. Not a pet for a home collection.' },
    // ---- more monitors: tree monitor group, Indo-Pacific water monitors, and the Australian dwarfs and giants ----
    // Australian species are legally kept only in Australia under state wildlife licences; they are here because those keepers exist.
    { n: 'Black tree monitor', g: 'Monitor', hot: 88, cool: 78, bask: 120, rh: [70, 90], rhShed: 90, night: 74, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '3 to 3.5 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Same care as the green tree monitor: tall, dense, humid, misted, and a lower basking surface than terrestrial monitors. All-black animals show heat stress fast; watch the basking time.' },
    { n: 'Yellow tree monitor', g: 'Monitor', hot: 88, cool: 78, bask: 120, rh: [70, 90], rhShed: 90, night: 74, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '2.5 to 3 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Tree monitor group, from Misool. Rare, expensive, and fragile in transit; captive-bred only.' },
    { n: 'Golden-spotted tree monitor', g: 'Monitor', hot: 88, cool: 78, bask: 120, rh: [70, 90], rhShed: 90, night: 74, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '2.5 to 3 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Tree monitor group (Varanus boehmei). Same husbandry as the green and black tree monitors.' },
    { n: 'Turquoise / cerulean monitor', g: 'Monitor', hot: 88, cool: 78, bask: 125, rh: [70, 85], rhShed: 90, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, fish, occasional whole prey', size: '3.5 to 4 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Mangrove group (Varanus caerulivirens), not a tree monitor despite the color. Semi-aquatic, humid, and shy.' },
    { n: 'Kordo tree monitor', g: 'Monitor', hot: 88, cool: 78, bask: 120, rh: [70, 90], rhShed: 90, night: 74, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '2.5 to 3 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Biak Island tree monitor (Varanus kordensis). Tree monitor care; almost never captive-bred, so quarantine hard.' },
    { n: 'Spotted tree monitor', g: 'Monitor', hot: 90, cool: 78, bask: 135, rh: [50, 70], rhShed: 80, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, occasional egg or pinky', size: '18 to 24 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Australian dwarf (Varanus scalaris), semi-arboreal and drier than the Indonesian tree monitors. Licence required in Australia.' },
    { n: 'Gillen\'s pygmy monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [40, 60], rhShed: 70, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, occasional pinky', size: '12 to 16 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Australian dwarf, arboreal, lives in tree hollows: vertical cork with tight crevices. Licence required in Australia.' },
    { n: 'Kingorum monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [40, 60], rhShed: 70, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects', size: '10 to 14 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'One of the smallest monitors; rock-dwelling. Stacked slate secured against collapse. Licence required in Australia.' },
    { n: 'Short-tailed pygmy monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [40, 60], rhShed: 70, night: 75, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Small insects', size: '8 to 10 in', life: '8 to 12 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'The smallest monitor (Varanus brevicauda), a burrower in spinifex country. Deep sand-soil mix. Australia only.' },
    { n: 'Long-tailed rock monitor', g: 'Monitor', hot: 90, cool: 78, bask: 135, rh: [50, 60], rhShed: 75, night: 74, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, small lizards, occasional pinky', size: '2.5 to 3 ft, mostly tail', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Varanus glebopalma, a fast rock-crevice species with a tail twice its body. Wide, low rockwork. Licence required in Australia.' },
    { n: 'Rainbow / blue-tailed monitor', g: 'Monitor', hot: 90, cool: 80, bask: 130, rh: [70, 85], rhShed: 90, night: 76, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, fish, eggs, occasional whole prey', size: '3 to 4 ft', life: '12 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Mangrove group (Varanus doreanus): humid, semi-aquatic, large water area with filtration. Imports need a fecal test before anything else.' },
    { n: 'Ornate monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [70, 85], rhShed: 85, night: 76, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Insects, fish, crustaceans, whole prey', size: '5 to 7 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'The forest form of the Nile monitor (Varanus ornatus). Same size, same speed, same restrictions in some states: check the law.' },
    { n: 'Yellow-headed water monitor', g: 'Monitor', hot: 92, cool: 82, bask: 135, rh: [70, 90], rhShed: 90, night: 78, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Fish, insects, crustaceans, whole prey, eggs', size: '5 to 6 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Philippine water monitor (Varanus cumingi). Heated room with a pool, like the Asian water monitor; slightly calmer by reputation, still a large animal.' },
    { n: 'Mertens\' water monitor', g: 'Monitor', hot: 90, cool: 80, bask: 130, rh: [70, 90], rhShed: 90, night: 76, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Fish, crustaceans, insects, occasional whole prey', size: '3 to 4 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Australian, almost fully aquatic: more pool than land, with filtration sized for a heavy feeder. Licence required in Australia.' },
    { n: 'Mitchell\'s water monitor', g: 'Monitor', hot: 90, cool: 80, bask: 130, rh: [70, 90], rhShed: 90, night: 76, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Fish, insects, crustaceans', size: '2 to 2.5 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Smaller Australian water monitor, semi-arboreal over water: branches above a deep pool. Licence required in Australia.' },
    { n: 'Lace monitor', g: 'Monitor', hot: 92, cool: 80, bask: 140, rh: [50, 70], rhShed: 80, night: 74, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Whole prey, eggs, insects', size: '5 to 6.5 ft', life: '20 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Australian giant, arboreal and strong: an aviary-sized enclosure with vertical trunks. Advanced licence class in most states.' },
    { n: 'Sand goanna / Gould\'s monitor', g: 'Monitor', hot: 95, cool: 80, bask: 145, rh: [40, 60], rhShed: 70, night: 74, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Insects, whole prey, eggs', size: '4 to 5 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Australian, terrestrial, a digger: 2 ft of substrate and a hot dry surface. Licence required in Australia.' },
    { n: 'Spencer\'s monitor', g: 'Monitor', hot: 95, cool: 80, bask: 140, rh: [40, 60], rhShed: 70, night: 74, uvb: 'Required, high', interval: 3, juv: 2, diet: 'Insects, whole prey, eggs', size: '3 to 4 ft', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Australian black-soil plains species, a heavy digger. Licence required in Australia.' },
    { n: 'Perentie', g: 'Monitor', hot: 95, cool: 80, bask: 150, rh: [30, 50], rhShed: 60, night: 74, uvb: 'Required, high', interval: 4, juv: 2, diet: 'Whole prey, eggs, insects', size: '6 to 8 ft', life: '20 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Australia\'s largest lizard. Kept only under the highest licence classes, in room-sized or outdoor enclosures. Not available outside Australia.' },
    // ---- tortoises and turtles ----
    { n: 'Russian tortoise', g: 'Tortoise', hot: 85, cool: 72, bask: 98, rh: [40, 60], rhShed: null, night: 65, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Weeds and leafy greens daily; no fruit, no protein', size: '6 to 10 in', life: '40+ years', supp: 'Calcium on greens 2 to 3 times a week', note: 'Digs and escapes; enclosure walls sunk or reinforced. Brumates in winter.' },
    { n: 'Hermann\'s tortoise', g: 'Tortoise', hot: 85, cool: 72, bask: 95, rh: [50, 70], rhShed: null, night: 65, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Weeds and greens daily', size: '6 to 8 in', life: '50+ years', supp: 'Calcium on greens 2 to 3 times a week', note: 'Mediterranean species; outdoor time in warm weather is a real benefit.' },
    { n: 'Sulcata tortoise', g: 'Tortoise', hot: 90, cool: 75, bask: 100, rh: [40, 60], rhShed: null, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Grasses and hay, low protein', size: '24 to 30 in, 70 to 150 lb', life: '70+ years', supp: 'Calcium on greens', note: 'Becomes a livestock-scale animal needing a heated outdoor shed. Plan for decades.' },
    { n: 'Red-footed tortoise', g: 'Tortoise', hot: 88, cool: 75, bask: 95, rh: [70, 80], rhShed: null, night: 72, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Greens, fruit, some protein weekly', size: '11 to 14 in', life: '50+ years', supp: 'Calcium on greens 2 to 3 times a week', note: 'Tropical: humidity high, no brumation.' },
    { n: 'Leopard tortoise', g: 'Tortoise', hot: 88, cool: 75, bask: 100, rh: [40, 60], rhShed: null, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Grasses and hay; no protein', size: '14 to 18 in', life: '50+ years', supp: 'Calcium on greens', note: 'Does not brumate; sensitive to cold and damp.' },
    { n: 'Red-eared slider', g: 'Turtle', hot: null, cool: null, bask: 92, rh: null, rhShed: null, night: null, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Pellets, greens, occasional protein; adults every other day', size: '8 to 12 in', life: '20 to 30 years', supp: 'Calcium block or cuttlebone in the water', note: 'Water 75 to 80F, strong filtration, a dry basking dock at 90 to 95F. Adults need 75 gallons or more.' },
    { n: 'Musk turtle', g: 'Turtle', hot: null, cool: null, bask: 90, rh: null, rhShed: null, night: null, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Pellets, snails, insects', size: '3 to 5 in', life: '30 to 50 years', supp: 'Calcium block in the water', note: 'Water 72 to 78F; a poor swimmer, so keep water shallow enough to reach the surface easily.' },
    { n: 'Painted turtle', g: 'Turtle', hot: null, cool: null, bask: 90, rh: null, rhShed: null, night: null, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Pellets, greens, protein', size: '5 to 7 in', life: '25 to 30 years', supp: 'Calcium block in the water', note: 'Water 75 to 80F with a basking dock; needs strong filtration.' },
    // ---- amphibians kept alongside ----
    { n: 'Crested / White\'s tree frog', g: 'Amphibian', hot: 82, cool: 72, bask: null, rh: [50, 70], rhShed: null, night: 68, uvb: 'Optional, low', interval: 3, juv: 2, diet: 'Dusted insects', size: '3 to 5 in', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Obesity is the common problem; feed less than you think. Dechlorinated water only.' },
    { n: 'Pacman frog', g: 'Amphibian', hot: 82, cool: 75, bask: null, rh: [60, 80], rhShed: null, night: 72, uvb: 'Optional, low', interval: 4, juv: 2, diet: 'Dusted insects, occasional pinky', size: '4 to 7 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Burrows and waits; substrate must stay damp, never soaking. Dechlorinated water only.' },
    { n: 'Tiger salamander', g: 'Amphibian', hot: 68, cool: 60, bask: null, rh: [70, 80], rhShed: null, night: 58, uvb: 'None', interval: 3, juv: 2, diet: 'Earthworms, insects', size: '6 to 8 in', life: '10 to 15 years', supp: 'Calcium weekly', note: 'Cool species: above about 75F is dangerous. No heat lamp in most rooms.' },
    { n: 'Axolotl', g: 'Amphibian', hot: null, cool: null, bask: null, rh: null, rhShed: null, night: null, uvb: 'None', interval: 3, juv: 2, diet: 'Sinking pellets, earthworms', size: '9 to 12 in', life: '10 to 15 years', supp: 'None needed', note: 'Water 60 to 64F, no higher. Fine sand or bare bottom only; gravel causes impaction.' }
  ];
  const WIKI = {
    'King snake': 'Kingsnake', 'Sand boa': 'Kenyan sand boa', 'Hognose snake': 'Western hognose snake', 'Leopard gecko': 'Common leopard gecko',
    'Leachianus gecko': 'New Caledonian giant gecko', 'Day gecko (Phelsuma)': 'Phelsuma', 'Bearded dragon': 'Central bearded dragon', 'Blue-tongue skink': 'Blue-tongued skink',
    'Green anole': 'Carolina anole', 'Argentine tegu': 'Argentine black and white tegu', 'Crested / Chinese water dragon': 'Chinese water dragon', 'Leopard / ocellated skink': 'Ocellated skink',
    'Gold dust / common house gecko': 'Gold dust day gecko', 'Sulcata tortoise': 'African spurred tortoise', 'Musk turtle': 'Common musk turtle', 'Crested / White\'s tree frog': 'Australian green tree frog',
    'Pacman frog': 'Argentine horned frog', 'Ackie monitor (spiny-tailed)': 'Spiny-tailed monitor', 'Black-headed / freckled monitor': 'Black-headed monitor', 'White-throated monitor': 'Rock monitor',
    'Black-throated monitor': 'Rock monitor', 'Green tree monitor': 'Emerald tree monitor', 'Blue tree monitor': 'Blue-spotted tree monitor', 'Turquoise / cerulean monitor': 'Varanus caerulivirens',
    'Kordo tree monitor': 'Varanus kordensis', 'Gillen\'s pygmy monitor': 'Pygmy mulga monitor', 'Kingorum monitor': 'Varanus kingorum', 'Short-tailed pygmy monitor': 'Short-tailed monitor',
    'Long-tailed rock monitor': 'Varanus glebopalma', 'Rainbow / blue-tailed monitor': 'Blue-tailed monitor', 'Yellow-headed water monitor': 'Varanus cumingi', 'Sand goanna / Gould\'s monitor': 'Sand goanna',
    'Peach-throated monitor': 'Varanus jobiensis', 'Black roughneck monitor': 'Varanus rudicollis', 'Golden-spotted tree monitor': 'Varanus boehmei', 'Yellow tree monitor': 'Varanus reisingeri'
  };
  const out = S.map(s => ({
    name: s.n, group: s.g, wiki: WIKI[s.n] || s.n,
    warm: s.bask ? `${s.bask} basking` : (s.hot ? `${s.hot} warm side` : 'n/a'),
    cool: s.cool ? String(s.cool) : (s.g === 'Turtle' ? 'water 75 to 80' : 'n/a'),
    rh: s.rh ? `${s.rh[0]} to ${s.rh[1]}%` : 'aquatic',
    uvb: s.uvb, diet: s.diet, interval: s.interval, juvInterval: s.juv,
    targets: { hot: s.hot || '', cool: s.cool || '', bask: s.bask || '', rh: s.rh ? Math.round((s.rh[0] + s.rh[1]) / 2) : '' },
    rhShed: s.rhShed, night: s.night, size: s.size, life: s.life, supp: s.supp, note: s.note
  }));
  if (typeof module !== 'undefined' && module.exports) module.exports = out; else root.RLSpecies = out;
})(typeof window !== 'undefined' ? window : globalThis);
