/* Reptile Log - species reference data. Commonly published husbandry targets for healthy adults.
   Temperatures F. rh = relative humidity %. feedInterval = days between offerings for an adult.
   Sources are mainstream care guides; individuals, locality and life stage move these numbers. */
(function (root) {
  'use strict';
  const S = [
    // ---- snakes ----
    { n: 'Ball python', g: 'Snake', hot: 90, cool: 79, bask: null, rh: [55, 65], rhShed: 70, night: 75, uvb: 'Optional, low', interval: 12, juv: 6, diet: 'One appropriately sized frozen-thawed rodent', size: '3 to 5 ft', life: '20 to 30 years', supp: 'None needed', note: 'Long winter fasts are normal in healthy adults; log weight every two weeks instead of worrying.' },
    { n: 'Corn snake', g: 'Snake', hot: 86, cool: 75, bask: null, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Optional, low', interval: 10, juv: 5, diet: 'Frozen-thawed mouse', size: '4 to 5 ft', life: '15 to 20 years', supp: 'None needed', note: 'Escape artist: check the lid latch every visit.' },
    { n: 'King snake', g: 'Snake', hot: 86, cool: 75, bask: null, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Optional, low', interval: 10, juv: 5, diet: 'Frozen-thawed rodent', size: '3 to 6 ft', life: '15 to 20 years', supp: 'None needed', note: 'Housed alone, always: kingsnakes eat other snakes.' },
    { n: 'Milk snake', g: 'Snake', hot: 85, cool: 74, bask: null, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Optional, low', interval: 10, juv: 5, diet: 'Frozen-thawed rodent', size: '2 to 5 ft', life: '15 to 20 years', supp: 'None needed', note: 'Shy; plenty of hides on both sides.' },
    { n: 'Boa constrictor', g: 'Snake', hot: 90, cool: 80, bask: null, rh: [55, 70], rhShed: 75, night: 78, uvb: 'Optional, low', interval: 21, juv: 10, diet: 'Frozen-thawed rodent', size: '6 to 10 ft', life: '25 to 30 years', supp: 'None needed', note: 'Gets big and strong; a second person for handling once past about 6 ft.' },
    { n: 'Rosy boa', g: 'Snake', hot: 88, cool: 72, bask: null, rh: [30, 50], rhShed: 60, night: 68, uvb: 'Optional, low', interval: 10, juv: 6, diet: 'Frozen-thawed mouse', size: '2 to 3 ft', life: '18 to 25 years', supp: 'None needed', note: 'Dry species; wet substrate causes scale rot.' },
    { n: 'Sand boa', g: 'Snake', hot: 95, cool: 75, bask: null, rh: [30, 40], rhShed: 50, night: 72, uvb: 'Optional, low', interval: 10, juv: 6, diet: 'Frozen-thawed mouse', size: '1.5 to 3 ft', life: '20 years', supp: 'None needed', note: 'Burrows; deep aspen or sand-soil mix, expect to see only the head.' },
    { n: 'Hognose snake', g: 'Snake', hot: 90, cool: 75, bask: null, rh: [30, 50], rhShed: 60, night: 72, uvb: 'Optional, low', interval: 7, juv: 5, diet: 'Frozen-thawed mouse, scented if needed', size: '1.5 to 3 ft', life: '15 to 20 years', supp: 'None needed', note: 'Bluffing displays (hooding, playing dead) are theatre, not illness.' },
    { n: 'Carpet python', g: 'Snake', hot: 90, cool: 78, bask: 92, rh: [50, 60], rhShed: 70, night: 74, uvb: 'Optional, low', interval: 14, juv: 7, diet: 'Frozen-thawed rodent', size: '5 to 9 ft', life: '20 years', supp: 'None needed', note: 'Arboreal; branches and a high perch matter more than floor space.' },
    { n: 'Green tree python', g: 'Snake', hot: 86, cool: 76, bask: 88, rh: [60, 80], rhShed: 85, night: 74, uvb: 'Optional, low', interval: 14, juv: 7, diet: 'Frozen-thawed rodent, offered on the perch', size: '4 to 6 ft', life: '20 years', supp: 'None needed', note: 'Advanced keeper species; humidity and ventilation must both be right.' },
    { n: 'Garter snake', g: 'Snake', hot: 85, cool: 72, bask: 88, rh: [40, 60], rhShed: 65, night: 65, uvb: 'Optional, low', interval: 5, juv: 3, diet: 'Fish (thiaminase-free), earthworms, rodents', size: '2 to 3 ft', life: '10 years', supp: 'Calcium with D3 on fish', note: 'Feeds often; avoid goldfish and other thiaminase-rich fish.' },
    { n: 'Reticulated python', g: 'Snake', hot: 90, cool: 80, bask: null, rh: [60, 70], rhShed: 75, night: 78, uvb: 'Optional, low', interval: 21, juv: 10, diet: 'Frozen-thawed rodent or rabbit', size: '10 to 20 ft', life: '20 to 25 years', supp: 'None needed', note: 'Large constrictor: two adults present for any handling, and check local rules.' },
    { n: 'Blood python', g: 'Snake', hot: 88, cool: 78, bask: null, rh: [60, 70], rhShed: 75, night: 76, uvb: 'Optional, low', interval: 14, juv: 7, diet: 'Frozen-thawed rodent', size: '4 to 6 ft', life: '20 years', supp: 'None needed', note: 'Heavy-bodied and humidity-sensitive; watch for respiratory signs if it dries out.' },
    // ---- geckos ----
    { n: 'Leopard gecko', g: 'Gecko', hot: 90, cool: 77, bask: null, rh: [30, 40], rhShed: 60, night: 70, uvb: 'Optional, low', interval: 3, juv: 1, diet: 'Dusted insects: crickets, dubia, black soldier fly larvae', size: '8 to 10 in', life: '15 to 20 years', supp: 'Calcium most feedings, D3 1 to 2x weekly without UVB, multivitamin every 1 to 2 weeks', note: 'Belly heat from a mat or DHP on a thermostat; a humid hide prevents stuck shed on toes.' },
    { n: 'Crested gecko', g: 'Gecko', hot: 78, cool: 70, bask: null, rh: [60, 80], rhShed: 80, night: 68, uvb: 'Optional, low', interval: 2, juv: 1, diet: 'Complete crested gecko diet, insects weekly', size: '7 to 9 in', life: '15 to 20 years', supp: 'In the diet; dust insects with calcium', note: 'Above about 82F is dangerous. Let the enclosure dry out between mistings.' },
    { n: 'Gargoyle gecko', g: 'Gecko', hot: 78, cool: 70, bask: null, rh: [60, 75], rhShed: 80, night: 68, uvb: 'Optional, low', interval: 2, juv: 1, diet: 'Complete gecko diet, insects weekly', size: '7 to 9 in', life: '15 to 20 years', supp: 'In the diet; dust insects with calcium', note: 'Same heat ceiling as cresteds; will eat other geckos, so house alone.' },
    { n: 'Leachianus gecko', g: 'Gecko', hot: 78, cool: 70, bask: null, rh: [60, 75], rhShed: 80, night: 68, uvb: 'Optional, low', interval: 3, juv: 2, diet: 'Complete gecko diet, insects, occasional pinky', size: '12 to 17 in', life: '20 years', supp: 'In the diet; calcium on insects', note: 'Largest gecko; tall enclosure with a cork tube.' },
    { n: 'African fat-tailed gecko', g: 'Gecko', hot: 90, cool: 77, bask: null, rh: [50, 60], rhShed: 70, night: 72, uvb: 'Optional, low', interval: 3, juv: 1, diet: 'Dusted insects', size: '7 to 9 in', life: '15 to 20 years', supp: 'Calcium most feedings, D3 weekly without UVB, multivitamin biweekly', note: 'Needs more humidity than a leopard gecko; always a moist hide.' },
    { n: 'Tokay gecko', g: 'Gecko', hot: 88, cool: 75, bask: null, rh: [60, 80], rhShed: 80, night: 72, uvb: 'Optional, low', interval: 3, juv: 1, diet: 'Dusted insects', size: '10 to 15 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Bites hard and does not let go. Display animal, not a handling animal.' },
    { n: 'Day gecko (Phelsuma)', g: 'Gecko', hot: 85, cool: 75, bask: 88, rh: [60, 80], rhShed: 80, night: 70, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects and fruit-based gecko diet', size: '5 to 10 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Diurnal and fast; delicate skin, handling is discouraged.' },
    // ---- lizards ----
    { n: 'Bearded dragon', g: 'Lizard', hot: 95, cool: 78, bask: 105, rh: [30, 40], rhShed: 50, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Adults mostly greens daily, insects 2 to 3 times a week', size: '18 to 24 in', life: '8 to 12 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Basking surface temperature, not air. No loose sand for juveniles.' },
    { n: 'Blue-tongue skink', g: 'Lizard', hot: 90, cool: 78, bask: 100, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Required, medium', interval: 3, juv: 2, diet: 'Omnivore mix: greens, vegetables, protein, some fruit', size: '18 to 24 in', life: '15 to 20 years', supp: 'Calcium on protein, multivitamin weekly', note: 'Indonesian species want higher humidity than Australian ones; check the locality.' },
    { n: 'Veiled chameleon', g: 'Lizard', hot: 82, cool: 72, bask: 90, rh: [50, 70], rhShed: 75, night: 65, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Dusted insects, adults every other day', size: '14 to 24 in', life: '5 to 8 years', supp: 'Calcium most feedings, D3 and multivitamin every 2 weeks', note: 'Screen enclosure, dripper or misting system; drinks moving water only.' },
    { n: 'Panther chameleon', g: 'Lizard', hot: 82, cool: 72, bask: 88, rh: [60, 80], rhShed: 80, night: 65, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Dusted insects', size: '14 to 20 in', life: '5 to 7 years', supp: 'Calcium most feedings, D3 and multivitamin every 2 weeks', note: 'Higher humidity than veiled; a night drop is normal and healthy.' },
    { n: 'Green anole', g: 'Lizard', hot: 85, cool: 72, bask: 90, rh: [60, 70], rhShed: 75, night: 65, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Small dusted insects', size: '5 to 8 in', life: '4 to 8 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Drinks droplets from leaves; mist daily.' },
    { n: 'Green iguana', g: 'Lizard', hot: 90, cool: 78, bask: 100, rh: [60, 80], rhShed: 80, night: 73, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Greens and vegetables daily, no animal protein', size: '5 to 6 ft', life: '15 to 20 years', supp: 'Calcium daily for juveniles, multivitamin weekly', note: 'Needs a room-sized enclosure as an adult. Most are rehomed; think hard first.' },
    { n: 'Argentine tegu', g: 'Lizard', hot: 90, cool: 78, bask: 105, rh: [60, 80], rhShed: 80, night: 72, uvb: 'Required, high', interval: 3, juv: 1, diet: 'Whole prey, insects, eggs, some fruit', size: '3 to 4.5 ft', life: '15 to 20 years', supp: 'Calcium on insects, multivitamin weekly', note: 'Brumates for months; deep substrate for burrowing.' },
    { n: 'Uromastyx', g: 'Lizard', hot: 95, cool: 80, bask: 120, rh: [20, 30], rhShed: 35, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Seeds, greens and flowers; no insects needed for most', size: '10 to 18 in', life: '15 to 20 years', supp: 'Calcium on greens, multivitamin weekly', note: 'Very hot and very dry; water bowls can cause problems, hydration comes from greens.' },
    { n: 'Crested / Chinese water dragon', g: 'Lizard', hot: 88, cool: 78, bask: 95, rh: [70, 80], rhShed: 85, night: 72, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Insects, some greens and protein', size: '2 to 3 ft', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Tall, planted, humid enclosure with a large water area; glass surfing damages the snout.' },
    { n: 'Leopard / ocellated skink', g: 'Lizard', hot: 90, cool: 75, bask: 95, rh: [40, 60], rhShed: 65, night: 70, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Insects and some plant matter', size: '6 to 12 in', life: '10 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Burrower; deep substrate and secure hides.' },
    { n: 'Gold dust / common house gecko', g: 'Gecko', hot: 85, cool: 75, bask: null, rh: [60, 70], rhShed: 75, night: 72, uvb: 'Optional, low', interval: 2, juv: 1, diet: 'Small dusted insects', size: '4 to 6 in', life: '5 to 10 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Fast and fragile; a display animal.' },
    // ---- tortoises and turtles ----
    { n: 'Russian tortoise', g: 'Tortoise', hot: 85, cool: 72, bask: 98, rh: [40, 60], rhShed: null, night: 65, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Weeds and leafy greens daily; no fruit, no protein', size: '6 to 10 in', life: '40+ years', supp: 'Calcium on greens 2 to 3 times a week', note: 'Digs and escapes; enclosure walls sunk or reinforced. Brumates in winter.' },
    { n: 'Hermann\'s tortoise', g: 'Tortoise', hot: 85, cool: 72, bask: 95, rh: [50, 70], rhShed: null, night: 65, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Weeds and greens daily', size: '6 to 8 in', life: '50+ years', supp: 'Calcium on greens 2 to 3 times a week', note: 'Mediterranean species; outdoor time in warm weather is a real benefit.' },
    { n: 'Sulcata tortoise', g: 'Tortoise', hot: 90, cool: 75, bask: 100, rh: [40, 60], rhShed: null, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Grasses and hay, low protein', size: '24 to 30 in, 70 to 150 lb', life: '70+ years', supp: 'Calcium on greens', note: 'Becomes a livestock-scale animal needing a heated outdoor shed. Plan for decades.' },
    { n: 'Red-footed tortoise', g: 'Tortoise', hot: 88, cool: 75, bask: 95, rh: [70, 80], rhShed: null, night: 72, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Greens, fruit, some protein weekly', size: '11 to 14 in', life: '50+ years', supp: 'Calcium on greens 2 to 3 times a week', note: 'Tropical: humidity high, no brumation.' },
    { n: 'Leopard tortoise', g: 'Tortoise', hot: 88, cool: 75, bask: 100, rh: [40, 60], rhShed: null, night: 70, uvb: 'Required, high', interval: 1, juv: 1, diet: 'Grasses and hay; no protein', size: '14 to 18 in', life: '50+ years', supp: 'Calcium on greens', note: 'Does not brumate; sensitive to cold and damp.' },
    { n: 'Red-eared slider', g: 'Turtle', hot: null, cool: null, bask: 92, rh: null, rhShed: null, night: null, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Pellets, greens, occasional protein; adults every other day', size: '8 to 12 in', life: '20 to 30 years', supp: 'Calcium block or cuttlebone in the water', note: 'Water 75 to 80F, strong filtration, a dry basking dock at 90 to 95F. Adults need 75 gallons or more.' },
    { n: 'Musk turtle', g: 'Turtle', hot: null, cool: null, bask: 90, rh: null, rhShed: null, night: null, uvb: 'Required, medium', interval: 2, juv: 1, diet: 'Pellets, snails, insects', size: '3 to 5 in', life: '30 to 50 years', supp: 'Calcium block in the water', note: 'Water 72 to 78F; a poor swimmer, so keep water shallow enough to reach the surface easily.' },
    { n: 'Painted turtle', g: 'Turtle', hot: null, cool: null, bask: 90, rh: null, rhShed: null, night: null, uvb: 'Required, high', interval: 2, juv: 1, diet: 'Pellets, greens, protein', size: '5 to 7 in', life: '25 to 30 years', supp: 'Calcium block in the water', note: 'Water 75 to 80F with a basking dock; needs strong filtration.' },
    // ---- amphibians kept alongside ----
    { n: 'Crested / White\'s tree frog', g: 'Amphibian', hot: 82, cool: 72, bask: null, rh: [50, 70], rhShed: null, night: 68, uvb: 'Optional, low', interval: 3, juv: 2, diet: 'Dusted insects', size: '3 to 5 in', life: '15 to 20 years', supp: 'Calcium most feedings, multivitamin weekly', note: 'Obesity is the common problem; feed less than you think. Dechlorinated water only.' },
    { n: 'Pacman frog', g: 'Amphibian', hot: 82, cool: 75, bask: null, rh: [60, 80], rhShed: null, night: 72, uvb: 'Optional, low', interval: 4, juv: 2, diet: 'Dusted insects, occasional pinky', size: '4 to 7 in', life: '10 to 15 years', supp: 'Calcium most feedings, multivitamin biweekly', note: 'Burrows and waits; substrate must stay damp, never soaking. Dechlorinated water only.' },
    { n: 'Tiger salamander', g: 'Amphibian', hot: 68, cool: 60, bask: null, rh: [70, 80], rhShed: null, night: 58, uvb: 'None', interval: 3, juv: 2, diet: 'Earthworms, insects', size: '6 to 8 in', life: '10 to 15 years', supp: 'Calcium weekly', note: 'Cool species: above about 75F is dangerous. No heat lamp in most rooms.' },
    { n: 'Axolotl', g: 'Amphibian', hot: null, cool: null, bask: null, rh: null, rhShed: null, night: null, uvb: 'None', interval: 3, juv: 2, diet: 'Sinking pellets, earthworms', size: '9 to 12 in', life: '10 to 15 years', supp: 'None needed', note: 'Water 60 to 64F, no higher. Fine sand or bare bottom only; gravel causes impaction.' }
  ];
  const out = S.map(s => ({
    name: s.n, group: s.g,
    warm: s.bask ? `${s.bask} basking` : (s.hot ? `${s.hot} warm side` : 'n/a'),
    cool: s.cool ? String(s.cool) : (s.g === 'Turtle' ? 'water 75 to 80' : 'n/a'),
    rh: s.rh ? `${s.rh[0]} to ${s.rh[1]}%` : 'aquatic',
    uvb: s.uvb, diet: s.diet, interval: s.interval, juvInterval: s.juv,
    targets: { hot: s.hot || '', cool: s.cool || '', bask: s.bask || '', rh: s.rh ? Math.round((s.rh[0] + s.rh[1]) / 2) : '' },
    rhShed: s.rhShed, night: s.night, size: s.size, life: s.life, supp: s.supp, note: s.note
  }));
  if (typeof module !== 'undefined' && module.exports) module.exports = out; else root.RLSpecies = out;
})(typeof window !== 'undefined' ? window : globalThis);
